In [2]:
import pandas as pd

In [7]:
df = pd.read_excel("data/jobs_skill_matrix_updated_v41.xlsx")

In [8]:
df.shape

(65, 948)

In [11]:
df.columns[:50].tolist()

['company',
 'role',
 'seniority',
 'python',
 'tensorflow',
 'pytorch',
 'natural_language_processing',
 'large_language_models',
 'generative_artificial_intelligence',
 'vector_databases',
 'recommendation_systems',
 'model_deployment',
 'model_optimization',
 'computer_vision',
 'sql',
 'pandas',
 'jupyter',
 'c++',
 'rust',
 'elasticsearch',
 'information_retrieval',
 'distributed_computing',
 'google_cloud_platform',
 'financial_services',
 'stakeholder_management',
 'sales',
 'cloud_computing',
 'artificial_intelligence_strategy',
 'enterprise_technology',
 'digital_transformation',
 'consultative_selling',
 'presentation_skills',
 'relationship_building',
 'customer_engagement',
 'enterprise_artificial_intelligence_transformation',
 'r',
 'statistical_analysis',
 'optimization_models',
 'data_dashboards',
 'exploratory_data_analysis',
 'business_data_science',
 'marketing_analytics',
 'data_validation',
 'data_quality',
 'data_security',
 'business_strategy',
 'metrics_development',
 'reporting',
 'data_visualization',
 'leadership_communication']

In [12]:
len(df.columns)

948

In [15]:
basic_cols = ["company", "role", "seniority"]
skill_cols = [col for col in df.columns if col not in basic_cols]
df["interpersonal_skills_list"] = df[skill_cols].apply(
    lambda row: [skill for skill in skill_cols if row[skill]== 1],
    axis=1
)
df[["company", "role", "seniority","interpersonal_skills_list"]].head()

,company,role,seniority,interpersonal_skills_list
0,shopify,machine learning applied scientist,senior,"[python, tensorflow, pytorch, natural_language..."
1,shopify,machine learning engineer - search,senior,"[python, natural_language_processing, large_la..."
2,loblaw companies limited,"analyst, data operations",junior,"[python, sql, pandas, jupyter]"
3,google,"senior software engineer, artificial intellige...",senior,"[python, natural_language_processing, large_la..."
4,google,"senior software engineer, artificial intellige...",senior,"[python, natural_language_processing, large_la..."

# NLP Preparation

In [ ]:
df["job_text"] = (
    df["role"].fillna("")+ " "+
    df["seniority"].fillna("")+" "+
    df["interpersonal_skills_list"].apply(lambda x: " ".join(x))
)

/var/folders/s0/xx7dqt192j9572kb3v34spg00000gn/T/ipykernel_75703/2028597268.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["job_text"] = (

In [17]:
df[["company","role","job_text"]].head()

,company,role,job_text
0,shopify,machine learning applied scientist,machine learning applied scientist senior pyth...
1,shopify,machine learning engineer - search,machine learning engineer - search senior pyth...
2,loblaw companies limited,"analyst, data operations","analyst, data operations junior python sql pan..."
3,google,"senior software engineer, artificial intellige...","senior software engineer, artificial intellige..."
4,google,"senior software engineer, artificial intellige...","senior software engineer, artificial intellige..."

# Embeddings

In [18]:
from sentence_transformers import SentenceTransformer

In [19]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 20641.85it/s]

# Create Embeddings For All 65 Jobs

In [20]:
job_embeddings = model.encode(
    df["job_text"].tolist(),
    show_progress_bar = True
)

Batches: 100%|██████████| 3/3 [00:02<00:00,  1.11it/s]

In [21]:
job_embeddings.shape

(65, 384)

In [22]:
sample_resume = """
Python
SQL
Machine Learning
Natural Language Processing
Large Language Models
PyTorch
TensorFlow
Data Analysis
"""

# Resume Matching

In [24]:
resume_embedding = model.encode(sample_resume)
resume_embedding

array([-3.47157829e-02, -1.15972258e-01,  6.04498340e-03,  3.21750268e-02,
        1.43479407e-02, -7.98009709e-03,  4.23936732e-02, -5.17938696e-02,
       -8.87848511e-02, -5.07160909e-02, -5.71954213e-02, -1.01672923e-02,
       -3.80304493e-02, -3.05101778e-02,  6.68516150e-03,  9.53115225e-02,
       -6.45304993e-02,  2.62999255e-02, -5.18986806e-02, -8.43846947e-02,
       -1.15898177e-02,  8.64691958e-02,  3.88677604e-03,  3.27908397e-02,
        2.94800252e-02, -8.95598670e-04,  1.76868699e-02, -1.89213138e-02,
        3.02911084e-02,  5.83901964e-02, -3.06122936e-02,  9.34301782e-03,
        1.88594554e-02,  1.30704880e-01,  1.23598706e-02, -6.28157286e-03,
       -8.90421718e-02, -3.68487053e-02, -1.49704041e-02, -4.52464931e-02,
        5.32513112e-02, -2.76948567e-02, -3.82213704e-02, -4.24597456e-05,
        8.61702934e-02, -2.61347517e-02, -2.47534197e-02, -4.11496349e-02,
        2.13045515e-02,  5.40651148e-03, -1.32383391e-01,  1.35365799e-02,
       -2.81776208e-02,  6.12767823e-02, -2.01648325e-02,  1.77941844e-02,
        4.58694138e-02, -1.79152209e-02, -4.28784601e-02, -5.51126599e-02,
       -1.00311339e-01, -1.09609425e-01, -9.55228787e-03,  3.67704816e-02,
       -1.27047561e-02,  2.74673458e-02, -5.31226620e-02,  3.45204175e-02,
        1.53418295e-02, -7.82150477e-02, -5.70759885e-02,  1.98689625e-02,
       -9.73814502e-02,  7.74560645e-02, -3.18223760e-02,  1.21066170e-02,
        8.29592645e-02,  8.71437602e-04,  6.39347136e-02, -1.80822760e-02,
       -5.29154874e-02,  1.11957332e-02,  4.46801446e-02,  2.89006159e-03,
        7.61692375e-02, -9.16905105e-02,  7.32270181e-02,  2.88537592e-02,
        1.34418821e-02,  1.16913104e-02,  3.97214055e-04, -7.48543739e-02,
        7.93779939e-02,  1.54462699e-02,  3.42680910e-03,  5.65676130e-02,
       -1.59491803e-02, -8.48083422e-02,  3.76460850e-02,  3.85671481e-02,
       -6.48518931e-03,  5.30973077e-02, -9.49712354e-04,  4.59929556e-03,
       -5.06960973e-02,  2.75876727e-02,  4.59708497e-02, -2.38850806e-02,
        2.00190973e-02, -7.43960738e-02,  5.76342130e-03,  1.91698689e-02,
        3.99978608e-02,  4.60714567e-03,  7.60952011e-02, -1.13055110e-02,
       -1.09970430e-02,  2.35670693e-02,  1.94715448e-02,  8.16009939e-02,
       -6.65872544e-02,  8.11734051e-02, -4.05123085e-02,  3.66936773e-02,
       -3.42456438e-02, -8.13368417e-04, -1.95921864e-02,  3.61494268e-33,
        1.23389782e-02,  1.61809148e-03,  4.96472195e-02, -1.01605959e-01,
        8.14756006e-02,  1.43363625e-02,  4.17833664e-02,  2.30328199e-02,
       -6.56667259e-03,  1.32845053e-02, -3.03762853e-02,  2.76769083e-02,
       -3.66895422e-02,  1.27591435e-02, -3.54592539e-02,  1.21798683e-02,
       -9.26293060e-03,  7.64958113e-02, -1.18102999e-02,  7.50022456e-02,
        5.78623340e-02, -3.54868523e-03, -4.84927977e-03,  6.22829311e-02,
        1.61994658e-02, -1.41695840e-02,  2.97266934e-02, -1.81428913e-03,
       -4.21521887e-02,  3.90249491e-02, -1.35431841e-01, -8.82796049e-02,
       -7.22897947e-02,  2.25908458e-02,  9.23949759e-03, -7.14636371e-02,
        1.82212330e-02, -7.42121483e-04,  1.47569729e-02, -5.82215078e-02,
       -9.09481645e-02,  1.70075726e-02, -2.31917407e-02, -1.33208744e-02,
       -8.64291564e-02,  1.84810627e-02, -4.71820403e-03, -1.15832696e-02,
        2.09748112e-02, -4.00217883e-02,  3.84200327e-02, -8.63229483e-02,
       -2.82323863e-02,  5.70704751e-02,  6.46938607e-02,  2.87642665e-02,
        6.81814626e-02,  3.52734551e-02,  8.82209092e-02, -2.75844987e-03,
        2.80663557e-02, -2.06948314e-02,  7.13032037e-02, -1.06725413e-02,
        5.38645200e-02,  2.11727694e-02, -4.46149856e-02,  6.91134110e-02,
        4.13033105e-02, -1.56123098e-02, -2.42088828e-02,  6.26773238e-02,
       -1.78187769e-02, -5.63194603e-02,  2.11163200e-02, -4.48701456e-02,
        2.94111054e-02, -8.76717567e-02,  1.21767493e-02,  1.26737967e-01,
       -5.02574779e-02, -2.38961019e-02, -7.32649304e-03, -5.15677929e-02,
       -9.19324309e-02, -5.50273620e-02,  1.44395670e-02, -1.24726566e-02,
        1.87100787e-02, -5.36253164e-03, -5.99541888e-02,  3.50633375e-02,
        6.47527277e-02, -3.15576955e-03, -4.89667244e-02, -3.11010863e-33,
       -5.52003086e-02, -8.44146241e-04, -4.79068309e-02,  4.63514924e-02,
       -1.51908109e-02, -8.55755433e-02, -3.99538465e-02,  9.25274268e-02,
        8.10323209e-02, -5.49695501e-03,  2.48128306e-02, -6.74418509e-02,
        7.11795166e-02, -3.80997695e-02,  8.05671364e-02,  4.69699465e-02,
        4.76234592e-02,  8.96147862e-02,  4.22390886e-02,  1.38840422e-01,
       -2.86364146e-02,  1.34825155e-01, -9.58254561e-02,  2.39390042e-02,
       -1.79821197e-02, -4.06088829e-02, -5.47049269e-02, -4.08657640e-02,
       -2.96787191e-02,  3.26746069e-02, -2.92735174e-02, -3.49350981e-02,
       -6.76333010e-02,  3.63960559e-03, -1.92637574e-02, -3.07433289e-02,
        3.53417732e-02, -9.65779945e-02,  3.11227106e-02,  5.58950938e-02,
        1.18947260e-01,  7.99081624e-02, -6.51784167e-02,  7.54508302e-02,
       -1.64545830e-02, -2.02055555e-02, -3.99517044e-02, -1.70166546e-03,
       -4.60393652e-02, -2.73914039e-02,  2.99135526e-03, -1.78888962e-02,
       -5.94421895e-03,  4.30367980e-03, -1.30467750e-02, -4.05682698e-02,
        8.25372264e-02, -7.72290528e-02, -5.54666109e-02, -2.69496404e-02,
       -6.55793473e-02,  2.99057513e-02,  4.93245572e-02, -1.10671051e-01,
        4.51143049e-02, -2.72749681e-02, -9.07166302e-02,  7.67561793e-02,
       -3.61847356e-02, -3.85769121e-02,  5.44067333e-03, -2.56025903e-02,
        2.66380943e-02,  1.40336156e-01, -2.18933057e-02,  4.48647775e-02,
       -1.90902147e-02, -3.32409106e-02, -1.71105098e-02,  5.00685610e-02,
        1.84637457e-02, -1.90564394e-02,  5.38401008e-02,  3.06156799e-02,
        6.15333766e-03,  5.02908528e-02,  6.45807153e-03,  2.13077050e-02,
        2.38229311e-03,  4.41576578e-02, -5.94348600e-03, -3.35030742e-02,
        3.93180437e-02,  9.22048241e-02,  7.83485360e-03, -1.70201115e-08,
       -6.62795901e-02,  7.18158558e-02, -1.91538513e-03,  2.47662086e-02,
        6.68231249e-02, -5.72792515e-02, -1.64544098e-02,  1.30027905e-01,
       -2.50171982e-02, -7.19418749e-03, -1.98567230e-02,  4.46367525e-02,
       -6.62483601e-03, -3.68903764e-02, -6.01192657e-03,  1.39647231e-01,
       -1.90950762e-02, -1.67383477e-02,  2.53101327e-02,  1.12332320e-02,
        1.25873297e-01,  1.80347878e-02, -1.99640021e-02,  3.94423716e-02,
       -6.88707605e-02, -2.81854868e-02, -3.68051417e-02,  7.03539029e-02,
       -4.40381244e-02, -6.00904077e-02, -1.64393825e-03, -2.74440292e-02,
       -7.93774202e-02, -5.40130511e-02,  9.53540355e-02,  3.13831754e-02,
        5.54304719e-02, -6.73876256e-02,  6.73486991e-03,  6.28674310e-03,
       -4.38199379e-02, -1.15874792e-02, -3.90689373e-02, -8.98812059e-03,
        3.23440172e-02, -1.45869805e-02, -6.14031628e-02, -6.29168302e-02,
        3.06665469e-02,  4.54666652e-03,  4.33662198e-02, -4.40860577e-02,
        2.35457020e-03,  6.63825944e-02,  8.08473602e-02,  2.69641299e-02,
       -1.90458819e-02,  2.68195588e-02, -4.64084791e-03, -6.14845529e-02,
       -2.96174325e-02,  7.25836381e-02,  9.44898203e-02,  5.75590366e-03],
      dtype=float32)

In [25]:
resume_embedding.shape

(384,)

# Calculate Similarity

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
similarities = cosine_similarity(
    [resume_embedding],
    job_embeddings
)

In [29]:
similarities.shape

(1, 65)

# Add Match Scores to DataFrame

In [30]:
df["match_score"]= similarities[0]
df[["company","role", "seniority" , "match_score"]].head()

/var/folders/s0/xx7dqt192j9572kb3v34spg00000gn/T/ipykernel_75703/696460036.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["match_score"]= similarities[0]

,company,role,seniority,match_score
0,shopify,machine learning applied scientist,senior,0.736840
1,shopify,machine learning engineer - search,senior,0.480247
2,loblaw companies limited,"analyst, data operations",junior,0.370092
3,google,"senior software engineer, artificial intellige...",senior,0.385682
4,google,"senior software engineer, artificial intellige...",senior,0.385682

# Top 10 matches

In [31]:
top_matches = (
    df[["company","role", "seniority" , "match_score"]]
    .sort_values("match_score", ascending= False)
)
top_matches.head(10)

,company,role,seniority,match_score
0,shopify,machine learning applied scientist,senior,0.736840
42,robertson & company ltd.,data scientist,mid,0.567003
19,insight global,data analyst,junior,0.561829
44,hays,machine learning engineer,mid,0.520127
61,hays,machine learning engineer,mid,0.517437
23,braze,"data scientist, artificial intelligence deploy...",mid,0.504185
32,scotiabank,"scientist - data, global artificial intelligen...",senior,0.490976
62,boardy,ai software engineer,mid,0.488879
51,qualcomm,ai/machine learning research engineer,senior,0.487576
33,ibm,machine learning developer intern,junior,0.484643

# Convert score to percentage

In [41]:

top_matches =  df[["company","role", "seniority" , "match_score"]].copy()
top_matches["match_percent"] = (
    top_matches["match_score"] * 100
).round(2)
top_matches["match_percent"] = top_matches["match_percent"].map(
    lambda x: f"{x:.2f}"
)

top_matches = top_matches.sort_values("match_score", ascending= False)
top_matches.head(10)

,company,role,seniority,match_score,match_percent
0,shopify,machine learning applied scientist,senior,0.736840,73.68
42,robertson & company ltd.,data scientist,mid,0.567003,56.70
19,insight global,data analyst,junior,0.561829,56.18
44,hays,machine learning engineer,mid,0.520127,52.01
61,hays,machine learning engineer,mid,0.517437,51.74
23,braze,"data scientist, artificial intelligence deploy...",mid,0.504185,50.42
32,scotiabank,"scientist - data, global artificial intelligen...",senior,0.490976,49.10
62,boardy,ai software engineer,mid,0.488879,48.89
51,qualcomm,ai/machine learning research engineer,senior,0.487576,48.76
33,ibm,machine learning developer intern,junior,0.484643,48.46

# Extract Test(PYPDF)

In [ ]:
from pypdf import PdfReader
reader = PdfReader("data/SAJEDEH KHALEDI_CV.pdf")
resume_text = ""

for page in reader.pages:
    resume_text += page.extract_text()

print(resume_text[:1000])

Ignoring wrong pointing object 14 0 (offset 0)

SAJEDEH KHALEDI Machine Learning / Data Scientist | Montreal, QC, Canada sajedeh.khaledi1@gmail.com | +1 438-462-9545 GitHub: github.com/Saja28 | LinkedIn: linkedin.com/in/sajedeh-khaledi   PROFESSIONAL SUMMARY Machine Learning–focused Data Scientist with a strong engineering background and a Data Science certificate from Le Wagon (December 2025). Experienced in building end-to-end machine learning systems, from data processing and model training to deployment and monitoring. Combines control engineering foundations with applied ML to deliver scalable, production-ready solutions.   TECHNICAL SKILLS Machine Learning & Data Science: Python, SQL, Pandas, NumPy, Scikit-learn, TensorFlow, Keras Modeling & Analytics: Feature Engineering, Model Evaluation, Statistical Analysis MLOps & Deployment: REST APIs, Streamlit, Google Cloud Platform, MLflow, Docker, Git Engineering Foundations: Control Systems, Signal Processing, FPGA / VHDL (foundational), Embedded C, AutoCAD  PROJECTS     NoDoze   AI

# Create Real Resume Embedding

In [46]:
resume_embedding.shape

(384,)

# Compare real CV with 65 jobs

In [49]:
similarities = cosine_similarity(
    [resume_embedding],
    job_embeddings
)

In [53]:
df["match_score"] = similarities[0]

top_matches = df[["company", "role", "seniority", "match_score"]].copy()

top_matches["match_percent"] = (
    top_matches["match_score"]*100
).round(2)

top_matches["match_percent"] = top_matches["match_percent"].map(
    lambda x: f"{x:.2f}"
)

top_matches = top_matches.sort_values("match_score", ascending= False)

top_matches.head(10)

,company,role,seniority,match_score,match_percent
0,shopify,machine learning applied scientist,senior,0.736840,73.68
42,robertson & company ltd.,data scientist,mid,0.567003,56.70
19,insight global,data analyst,junior,0.561829,56.18
44,hays,machine learning engineer,mid,0.520127,52.01
61,hays,machine learning engineer,mid,0.517437,51.74
23,braze,"data scientist, artificial intelligence deploy...",mid,0.504185,50.42
32,scotiabank,"scientist - data, global artificial intelligen...",senior,0.490976,49.10
62,boardy,ai software engineer,mid,0.488879,48.89
51,qualcomm,ai/machine learning research engineer,senior,0.487576,48.76
33,ibm,machine learning developer intern,junior,0.484643,48.46

# Recalculate similarity with real CV

In [58]:
real_resume_embedding = model.encode(resume_text)

real_similarities = cosine_similarity(
    [real_resume_embedding],
    job_embeddings
)

df["real_cv_match_score"] = real_similarities[0]

real_top_matches = df[
    ["company", "role", "seniority", "real_cv_match_score"]
].copy()


real_top_matches["match_percent"] = (
    real_top_matches["real_cv_match_score"]*100
).round(2)

real_top_matches["match_percent"] = real_top_matches["match_percent"].map(
    lambda x: f"{x:.2f}"
)

real_top_matches = real_top_matches.sort_values(
    "real_cv_match_score",
    ascending= False
)

real_top_matches.head(10)

,company,role,seniority,real_cv_match_score,match_percent
61,hays,machine learning engineer,mid,0.609506,60.95
44,hays,machine learning engineer,mid,0.601392,60.14
33,ibm,machine learning developer intern,junior,0.594658,59.47
36,rbc,data & ai engineer,mid,0.539686,53.97
32,scotiabank,"scientist - data, global artificial intelligen...",senior,0.513809,51.38
43,bmo,associate data scientist,mid,0.512719,51.27
14,jobright.ai,machine learning engineer - early career,junior,0.507308,50.73
38,canadian tire corporation,data scientist,mid,0.489869,48.99
57,apexon,senior data scientist,senior,0.486742,48.67
47,aviva canada,data scientist,mid,0.485646,48.56

# Missing Skills Analysis

In [61]:
best_match_index = real_top_matches.index[0]

best_job_skills = df.loc[best_match_index, "interpersonal_skills_list"]

best_job_skills[:20]

['python',
 'pytorch',
 'recommendation_systems',
 'model_deployment',
 'google_cloud_platform',
 'data_analysis',
 'communication',
 'machine_learning',
 'data_preparation',
 'data_cleaning',
 'remote_work',
 'collaboration',
 'testing',
 'feature_engineering',
 'model_evaluation',
 'airflow',
 'production_machine_learning',
 'kubernetes',
 'version_control',
 'model_training']

# Extract skills from your real CV

In [62]:
resume_text_lower = resume_text.lower()

resume_skills = [
    skill for skill in skill_cols
    if skill.replace("_", " ") in resume_text_lower
]

resume_skills[:30]

['python',
 'tensorflow',
 'sql',
 'pandas',
 'google_cloud_platform',
 'sales',
 'r',
 'statistical_analysis',
 'data_analytics',
 'forecasting',
 'machine_learning',
 'tpu',
 'data_science',
 'dashboards',
 'tableau',
 'demand_forecasting',
 'engineering',
 'analytics',
 'feature_engineering',
 'model_evaluation',
 'docker',
 'monitoring',
 'git',
 'keras',
 'model_training',
 'scala',
 'mlops',
 'github',
 'numpy',
 'healthcare']

# Find the missing skills automatically

In [63]:
missing_skills = [
    skill
    for skill in best_job_skills
    if skill not in resume_skills
]

missing_skills

['pytorch',
 'recommendation_systems',
 'model_deployment',
 'data_analysis',
 'communication',
 'data_preparation',
 'data_cleaning',
 'remote_work',
 'collaboration',
 'testing',
 'airflow',
 'production_machine_learning',
 'kubernetes',
 'version_control',
 'apache_spark',
 'documentation',
 'deep_learning',
 'google_bigquery',
 'software_engineering',
 'inference_pipelines',
 'training_pipelines',
 'search_ranking_models',
 'google_dataflow',
 'cloud_workflows',
 'training_validation',
 'overfitting',
 'generalization',
 'evaluation_pipelines']

# Keep only important missing technical skills

In [64]:
important_missing_skills = [
    skill for skill in missing_skills
    if skill in [
        "pytorch",
        "recommendation_systems",
        "model_deployment",
        "airflow",
        "kubernetes",
        "apache_spark",
        "deep_learning",
        "google_bigquery",
        "inference_pipelines",
        "training_pipelines",
        "search_ranking_models",
        "evaluation_pipelines"
    ]
]

important_missing_skills

['pytorch',
 'recommendation_systems',
 'model_deployment',
 'airflow',
 'kubernetes',
 'apache_spark',
 'deep_learning',
 'google_bigquery',
 'inference_pipelines',
 'training_pipelines',
 'search_ranking_models',
 'evaluation_pipelines']

In [65]:
matched_skills = [
    skill
    for skill in best_job_skills
    if skill in resume_skills
]

matched_skills

['python',
 'google_cloud_platform',
 'machine_learning',
 'feature_engineering',
 'model_evaluation',
 'model_training']

In [66]:
len(matched_skills)

6

In [67]:
best_match = real_top_matches.iloc[0]

match_report = {
    "company": best_match["company"],
    "role": best_match["role"],
    "seniority": best_match["seniority"],
    "match_percent": best_match["match_percent"],
    "matched_skills": matched_skills,
    "important_missing_skills": important_missing_skills
}

match_report

{'company': 'hays',
 'role': 'machine learning engineer',
 'seniority': 'mid',
 'match_percent': '60.95',
 'matched_skills': ['python',
  'google_cloud_platform',
  'machine_learning',
  'feature_engineering',
  'model_evaluation',
  'model_training'],
 'important_missing_skills': ['pytorch',
  'recommendation_systems',
  'model_deployment',
  'airflow',
  'kubernetes',
  'apache_spark',
  'deep_learning',
  'google_bigquery',
  'inference_pipelines',
  'training_pipelines',
  'search_ranking_models',
  'evaluation_pipelines']}

In [68]:
print(f"Company: {match_report['company']}")
print(f"Role: {match_report['role']}")
print(f"Seniority: {match_report['seniority']}")
print(f"Match Score: {match_report['match_percent']}%")

print("\nMatched Skills:")
for skill in match_report["matched_skills"]:
    print(f"✅ {skill}")

print("\nImportant Missing Skills:")
for skill in match_report["important_missing_skills"]:
    print(f"❌ {skill}")

Company: hays
Role: machine learning engineer
Seniority: mid
Match Score: 60.95%

Matched Skills:
✅ python
✅ google_cloud_platform
✅ machine_learning
✅ feature_engineering
✅ model_evaluation
✅ model_training

Important Missing Skills:
❌ pytorch
❌ recommendation_systems
❌ model_deployment
❌ airflow
❌ kubernetes
❌ apache_spark
❌ deep_learning
❌ google_bigquery
❌ inference_pipelines
❌ training_pipelines
❌ search_ranking_models
❌ evaluation_pipelines

I built an NLP-powered Resume Matcher using Sentence Transformers and cosine similarity that analyzes job descriptions, ranks opportunities against a real resume, identifies missing skills, and generates personalized career recommendations.

# Gemini Resume Recommendations